Weaponized Adorables Negotiation Tactics

Rachel Law & McKenzie Wark: W.A.N.T: Weaponized Adorables Negotiation Tactics (2013)

“The art of digital living in the PRISM era. An illustrated book for art, tech & theory fans.

What is data? How do we perceive the difference between data and information? How do we define the size, shape and scale of a network? Where do we even begin? These are the fundamental questions we are trying to address in W.A.N.T.

Digital living is under an onslaught of Weaponized Adorables. They are coming for you. You will be mugged in the bright alleys of your dreams by the teddy bear horde. What you can deploy on your side is your own W.A.N.T, or Weaponized Adorables Negotiation Team. This little manual we will introduce you to them, they are like a set of superheroes ready to fight on this digital terrain.” (from the project’s Kickstarter page)

Published via Kickstarter
Creative Commons Attribution Non-Commercial ShareAlike 3.0 License
80 pages
via Marcell Mars
